name: "SAAAC - SA Academy of Applied Competence"
description: "Educate Empower Employ"
main_keywords: "Keyword"
author: "Me"
copyright: "2013"
paginate: 20


# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        :title

# Server
base_url: /

# Custom vars

