name: "SAAAC - SA Academy of Applied Competence"
description: "Educate Empower Employ - Quality Education at Affordable Prices"
main_keywords: "Education"
author: "Wayne Lardner"
copyright: "2013"
paginate: 20


# Dependencies
markdown:         rdiscount
pygments:         true

# Permalinks
permalink:        :title

# Server
base_url: /

# Custom vars

